name: 'Build Extension'

description: 'Runs necessary steps to build the TFX extension.'

inputs:
  task-path:  
    description: 'The path to the TFX path.'
    required: true
  task-publish-pat:  
    description: 'The PAT to use to publish the task.'
    required: true
    default: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  test-queue-pat:  
    description: 'The PAT to use to queue the test.'
    required: true
    default: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}
  bot-pat:  
    description: 'The PAT to use to queue the test.'
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}

runs:
  using: "composite"

  steps:
  - uses: actions/checkout@v2

  - name: Setup Node
    uses: actions/setup-node@v1
    with:
      node-version: '10.x'

  - name: NPM install with caching
    uses: bahmutov/npm-install@v1.6.0
    with:
      working-directory: ${{ inputs.task-path }} # ./NotionReleaseNotes/

  - name: Compile Typescript
    run: |
      tsc -p ${{ inputs.task-path }}/tsconfig.json

  - name: TfxInstaller
    uses: Maetis/github-action-tfxinstaller@v1.0.0-pre

  - name: Publish Task
    env:
      AZURE_DEVOPS_EXT_PAT: ${{ inputs.task-publish-pat }}
    run: |
      tfx extension create --manifest-globs vss-extension.test.json
      tfx extension publish --manifest-globs vss-extension.test.json --share-with nictolhurst --token ${{ inputs.task-publish-pat }}

  - name: Trigger Task Run
    env:
      AZURE_DEVOPS_EXT_PAT: ${{ inputs.test-queue-pat }}
    uses: Azure/cli@1.0.4
    with:
      inlineScript: |
        az config set extension.use_dynamic_install=yes_without_prompt
        az repos pr policy queue --evaluation-id 96e348ff-825d-4e85-acc5-edfd29f76776 --id 28 --org https://dev.azure.com/nictolhurst/
        
  - uses: mshick/add-pr-comment@v1
    env:
      GITHUB_TOKEN: ${{ inputs.bot-pat }}
    with:
      message: |
        A test for your commit been triggered over at [Azure DevOps](https://nictolhurst.visualstudio.com/Awesome%20Project/_git/Awesome%20Project/pullrequest/29)
        
        When the task has compelted, your release notes will be available for review at [Notion Release Notes Tests](https://ethereal-coreopsis-b86.notion.site/3c0cf7a718e8404faa837870b25a2eef?v=28249579058948718b4ce06434256f82)
      allow-repeats: true