name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
    
      - name: NPM install with caching
        uses: bahmutov/npm-install@v1.6.0
        with:
          working-directory: ./NotionReleaseNotes/

      - name: Compile Typescript
        run: |
          tsc -p ./NotionReleaseNotes/tsconfig.json

      - name: TfxInstaller
        uses: Maetis/github-action-tfxinstaller@v1.0.0-pre

      - name: Publish Task
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 
        run: |
          tfx extension create --manifest-globs vss-extension.json
          tfx extension publish --manifest-globs vss-extension.json --token ${{ secrets.PERSONAL_ACCESS_TOKEN }}