# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
    
      - name: NPM install with caching
        uses: bahmutov/npm-install@v1.6.0
        with:
          working-directory: ./NotionReleaseNotes/

      - name: Compile Typescript
        run: |
          tsc -p ./NotionReleaseNotes/tsconfig.json

      - name: Update Build Version
        run: |
          ./update-version.ps1 -SemanticReleaseType "Build"
        shell: pwsh  

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: "apply version updates for PR #${{ github.event.number }}"
          branch: ${{ github.head_ref }}
          commit_options: --no-verify
          file_pattern: .

      - name: TfxInstaller
        uses: Maetis/github-action-tfxinstaller@v1.0.0-pre

      - name: Publish Task
        run: |
          tfx extension create --manifest-globs vss-extension.test.json
          tfx extension publish --manifest-globs vss-extension.test.json --share-with nictolhurst --token ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Trigger Task Run
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            az repos pr policy queue --evaluation-id 96e348ff-825d-4e85-acc5-edfd29f76776 --id 28 --org https://dev.azure.com/nictolhurst/
            
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            A test has been triggered over at [Azure DevOps](https://nictolhurst.visualstudio.com/Awesome%20Project/_git/Awesome%20Project/pullrequest/29)
            
            When the task has compelted, you're release notes will be available at [Notion Release Notes Tests](https://ethereal-coreopsis-b86.notion.site/3c0cf7a718e8404faa837870b25a2eef?v=28249579058948718b4ce06434256f82)
          allow-repeats: true
