name: UTILS

on:
  pull_request:
    branches: [ main ]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Update Build Version
        run: |
          ./update-version.ps1 -SemanticReleaseType "Build"
        shell: pwsh  

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: "apply version updates for PR #${{ github.event.number }}"
          branch: ${{ github.head_ref }}
          commit_options: --no-verify
          file_pattern: .
